adopciones/adopciones/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', include('inicio.urls')),
    path('mascotas/', include('mascotas.urls')),
    path('accounts/', include('registration.backends.default.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

adopciones/inicio/urls.py
from django.urls import path
from . import views

app_name = 'inicio'

urlpatterns = [
    path('', views.index, name='index'),
]

adopciones/mascotas/urls.py
from django.urls import path
from . import views

app_name = 'mascotas'

urlpatterns = [
    path('', views.index, name='index'),
]

adopciones/inicio/models.py
from django.db import models

# Create your models here.

adopciones/mascotas/models.py
from django.db import models
from django.utils.html import format_html # nos permite usar formato html

class Especie(models.Model):
    nombre = models.CharField(max_length=10, db_index=True)

    def __str__(self):
        return '%s' % self.nombre

class Mascota(models.Model):
    #tupla de opciones para el estado
    Adoptado = 'Adoptado'
    En_Adopcion = 'En adopción'
    ESTADO_MASCOTA = (
        (Adoptado, 'Adoptado'),
        (En_Adopcion, 'En adopción'),
    )

    estado = models.CharField(max_length=15, choices=ESTADO_MASCOTA, default='En adopción')
    nombre_mascota = models.CharField(max_length=200)
    sexo = models.CharField(max_length=20, default="No especificado")
    edad = models.IntegerField(default=0)
    fecha_publicacion = models.DateTimeField('Fecha de publicación')
    imagen = models.ImageField(upload_to="nombre_mascota/%Y/%m/%d", blank=True, null=True)
    especie = models.ForeignKey(
        Especie, blank=False, null=True, on_delete=models.CASCADE
    )


    def estado_de_mascota(self):
        if self.estado == 'Adoptado':
            return format_html('<span style="color: #f00;">{}</span>', self.estado, )
        elif self.estado == 'En adopción':
            return format_html('<span style="color: #f0f;">{}</span>', self.estado, )
    
    
    def __str__(self, ):
        return self.nombre_mascota

adopciones/inicio/views.py
from django.shortcuts import render

def index(request): #agrego un index básico para que no se rompa la aplicación
    
    return render(request, 'inicio/index.html')

adopciones/mascotas/views.py
from django.shortcuts import render
from .models import Mascota

def index(request):
    mascotas = Mascota.objects.filter(estado='En adopción')
    return render(request, "mascotas/index.html", {"mascotas": mascotas})




#def index(request): #agrego un index básico para que no se rompa la aplicación 
#    return render(request, 'mascotas/index.html')

adopciones/templates/base.html
{% load static %} <!--Para cargar estilos estáticos-->
<!DOCTYPE html>

<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Adopciones{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" 
        rel="stylesheet"
    >

    <!-- Mi CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>

<body class="d-flex flex-column min-vh-100">

    {% block body %}{% endblock %}

    <!-- FOOTER -->
    <footer class="mt-auto bg-light text-center text-muted py-3">
        <small>© 2025 Adopciones Lola — Todos los derechos reservados.</small>
    </footer> <!-- lo pongo en base en vez de layout para poder usar mt-auto -->

    <!-- Bootstrap JS -->
    <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js">
    </script>

</body>
</html>

adopciones/templates/inicio/index.html
{% extends "layout.html" %}

{% block title %}Inicio{% endblock %}

{% block content %}
    <h1>Adopciones Lola</h1>

    <!-- Carrusel -->

    <div id="carrusel" class="carousel slide">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carrusel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carrusel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carrusel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
            <img src="/media/c1.jpg" class="d-block w-100 carrusel-img" alt="...">
            </div>
            <div class="carousel-item">
            <img src="/media/c2.jpg" class="d-block w-100 carrusel-img" alt="...">
            </div>
            <div class="carousel-item">
            <img src="/media/c3.jpg" class="d-block w-100 carrusel-img" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carrusel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Anterior</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carrusel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Siguiente</span>
        </button>
    </div>

{% endblock %}

adopciones/templates/layout.html
{% extends "base.html" %}

{% block body %}

<!-- NAVBAR -->
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'inicio:index' %}">Adopciones Lola</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarNav" aria-controls="navbarNav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'inicio:index' %}">Inicio</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'mascotas:index' %}">Mascotas</a>
        </li>

      </ul>
    </div>
  </div>
</nav>

<!-- CONTENIDO PRINCIPAL -->
<div class="container">
    {% block content %}{% endblock %}
</div>


{% endblock %}

adopciones/templates/mascotas/index.html
{% extends "layout.html" %}

{% block title %}Mascotas{% endblock %}

{% block content %}
    <h1>Nuestras mascotas</h1>

    <!-- Cartas -->

    <div class="container mt-4">
        <div class="row">
            {% for mascota in mascotas %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
                
                <div class="card h-100">
                    <img src="{{ mascota.imagen.url }}" class="card-img-top card-img-fixed" alt="{{ mascota.nombre_mascota }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ mascota.nombre_mascota }}</h5>
                        <p class="card-text">Edad: {{ mascota.edad }}</p>
                        <p class="card-text">Sexo: {{ mascota.sexo }}</p>
                        <a href="#" class="btn btn-primary">Ver más</a>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}